name: Build and Publish Docker Image

# If Push on master
on:
  push:
    branches: [ master ]
    paths:
      - '**.py'
      - 'Dockerfile'
      - 'requirements.txt'

# General Environments variables
env:
  # Google Cloud Env
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

  # Image Env
  IMAGE: app-du-milieu
  TAG: build

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - name: Set up Cloud credentials
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - run: gcloud auth configure-docker

    - name: Build
      run: |-
        docker build \
          --tag "eu.gcr.io/$GCP_PROJECT_ID/$IMAGE:$TAG" \
          .

    - name: Publish
      run: docker push eu.gcr.io/$GCP_PROJECT_ID/$IMAGE:$TAG
