name: Continuous Integration & Deployment

on:
    push:
        branches: [ master ]
    pull_request:
    release:
        types: [ published ]

jobs:
    Build:
        name: Build app
        runs-on: ubuntu-latest

        steps:

            - name: Checkout
              uses: actions/checkout@v2

            - uses: actions/setup-python@v2
              with:
                python-version: '3.9'
                architecture: 'x64'

            - uses: actions/cache@v2
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                  ${{ runner.os }}-pip-

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pylint
                pip install wheel
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - uses: actions/upload-artifact@v2
              with:
                name: Build-Artifact
                #path: ./Build-Artifact


    Tests:
        name: Test app
        runs-on: ubuntu-latest
        needs: [ Build ]

        steps:
            - uses: actions/checkout@v2
            - uses: actions/download-artifact@v2
              with:
                name: Build-Artifact
                #path: ./Build-Artifact

            - name: Analysing the code with pylint
              run: |
                python -m pylint --fail-under=10 `find -regextype egrep -regex '(.*.py)$'` |
                tee pylint.txt
