name: Continuous Integration & Deployment

on:
    push:
        branches: [ master ]
    pull_request:
    release:
        types: [ published ]

jobs:
    Tests:
        name: Test app
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.9'
                architecture: 'x64'

            - name: Get Cache
              uses: actions/cache@v2
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                  ${{ runner.os }}-pip-
                  ${{ runner.os }}-

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install wheel
                pip install -r requirements.txt

            - name: Pylint
              run: |
                pip install pylint
                python -m pylint --fail-under=10 `find -regextype egrep -regex '(.*.py)$'` |
                tee pylint.txt

            - name: Flake8
              run: |
                pip install flake8
                flake8 --ignore=E501,W505 .

            - name: PyTest
              run: |
                pip install pytest
                pip install pytest-cov
                pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
