name: Staging - Deploy to Cloud Run

on:
  workflow_run:
    workflows: ["Build and Publish Docker Image"]
    types:
      - completed


# General Environments variables
env:
  # Google Cloud Env
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_ZONE: ${{ secrets.GCP_ZONE }}

  # Cloud SQL Env
  SQL_INST: ${{ secrets.SQL_INST_STAGING }}
  DB_READ: ${{ secrets.DB_READ_STAGING }}
  DB_NAME: ${{ secrets.DB_NAME_STAGING }}
  DB_USER: ${{ secrets.DB_USER_STAGING }}
  DB_PASS: ${{ secrets.DB_PASS_STAGING }}

  # Image Env
  IMAGE: app-du-milieu
  TAG: build
  C_RUN_NAME: app-du-milieu-staging

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    # Setup gcloud CLI
    - name: Set up Cloud credentials
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name : Deploy Cloud Run
      run : |-
        gcloud run deploy $C_RUN_NAME \
        --image eu.gcr.io/$GCP_PROJECT_ID/$IMAGE:$TAG \
        --platform managed \
        --region $GCP_ZONE \
        --allow-unauthenticated \
        --ingress internal-and-cloud-load-balancing \
        --memory 1024Mi \
        --set-cloudsql-instances $SQL_INST \
        --set-env-vars=DB_USER=$DB_USER,DB_PASS=$DB_PASS,DB_NAME=$DB_NAME,DB_READ=$DB_READ,CLOUDSQL_CONN=$GCP_PROJECT_ID:$GCP_ZONE:$SQL_INST