name: Deploy to Cloud Run

on:
  workflow_run:
    workflows: ["Build and Publish Docker Image"]
    types: 
      - completed


# General Environments variables
env:
  # Google Cloud Env
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_ZONE: ${{ secrets.GCP_ZONE }}

  # Cloud SQL Env
  SQL_INST: ${{ secrets.SQL_INST_STAGING }}
  DB_NAME: ${{ secrets.DB_NAME_STAGING }}
  DB_USER: ${{ secrets.DB_USER_STAGING }}
  DB_PASS: ${{ secrets.DB_PASS_STAGING }}

  # Image Env
  IMAGE: middleware-api
  TAG: staging

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name : Deploy Cloud Run
      run : |-
        gcloud run deploy $IMAGE \
        --image eu.gcr.io/$GCP_PROJECT_ID/$IMAGE:$TAG \
        --platform managed \
        --region $GCP_ZONE \
        --allow-unauthenticated \
        --service-account ${{ secrets.GCP_SA_KEY }} \
        --ingress internal-and-cloud-load-balancing \
        --memory 128Mi \
        --set-cloudsql-instances $SQL_INST \
        --set-env-vars=DB_USER=$DB_USER,DB_PASS=$DB_PASS,DB_NAME=$DB_NAME,CLOUD_SQL_CONNECTION_NAME=$GCP_PROJECT_ID:$GCP_ZONE:$SQL_INST
