name: Release to Cloud Run

on:
  release:
    types:
      - released

# General Environments variables
env:
  # Google Cloud Env
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_ZONE: ${{ secrets.GCP_ZONE }}

  # Cloud SQL Env
  SQL_INST: ${{ secrets.SQL_INST_PROD }}
  DB_READ: ${{ secrets.DB_READ_PROD }}
  DB_NAME: ${{ secrets.DB_NAME_PROD }}
  DB_USER: ${{ secrets.DB_USER_PROD }}
  DB_PASS: ${{ secrets.DB_PASS_PROD }}

  # Image Env
  IMAGE: middleware-api
  IMAGE_NAME: middleware-api
  TAG: staging

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    # Setup gcloud CLI
    - name: Set up Cloud credentials
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name : Deploy Cloud Run
      run : |-
        gcloud run deploy $IMAGE_NAME \
        --image eu.gcr.io/$GCP_PROJECT_ID/$IMAGE:$TAG \
        --platform managed \
        --region $GCP_ZONE \
        --allow-unauthenticated \
        --ingress internal-and-cloud-load-balancing \
        --memory 2048Mi \
        --set-cloudsql-instances $SQL_INST \
        --set-env-vars=DB_USER=$DB_USER,DB_PASS=$DB_PASS,DB_NAME=$DB_NAME,DB_READ=$DB_READ,CLOUD_SQL_CONN=$GCP_PROJECT_ID:$GCP_ZONE:$SQL_INST
